---
services:
  - docker

stages:
  - common
  - images
  - deploy

jobs:
  include:
    - stage: common
      name: Build common
      script: make common
    - stage: images
      name: Build activity-harvester
      script: make image activity-harvester
      isolated: true
    - stage: images
      name: Build account-harvester
      script: make image account-harvester
      isolated: true
    - stage: images
      name: Build video-harvester
      script: make image video-harvester
      isolated: true
    - stage: images
      name: Build guardian-theater
      script: make image guardian-theater
      isolated: true
    - stage: deploy
      name: Deploy
      script: make deploy
