{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "guardian-theater.serviceAccountName" . }}
  labels:
{{ include "guardian-theater.labels" . | nindent 4 }}
{{- end -}}
